// Optional hook plugin installer. Writes to
// ~/.claude/plugins/agent-world/{plugin.json, hooks/status-hook.sh}
// and NEVER edits ~/.claude/settings.json.
//
// The hook script appends one JSON line per event into
// ~/.claude/plugins/agent-world/events/<pid>.jsonl, which the snapshotter
// consumes alongside (or instead of) claude-control's events dir.

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const PLUGIN_DIR = path.join(os.homedir(), '.claude', 'plugins', 'agent-world');
const HOOKS_DIR = path.join(PLUGIN_DIR, 'hooks');
const EVENTS_DIR = path.join(PLUGIN_DIR, 'events');
const PLUGIN_JSON = path.join(PLUGIN_DIR, 'plugin.json');
const HOOK_SCRIPT = path.join(HOOKS_DIR, 'status-hook.sh');
const PRE_TOOL_HOOK_SCRIPT = path.join(HOOKS_DIR, 'pre-tool-use-hook.sh');

const HOOK_EVENTS = [
  'SessionStart', 'SessionEnd', 'Stop', 'UserPromptSubmit',
  'PermissionRequest', 'SubagentStart', 'SubagentStop',
  'PostToolUseFailure', 'CwdChanged'
];

function pluginJsonContent() {
  const statusHooks = Object.fromEntries(HOOK_EVENTS.map(ev => [ev, {
    command: HOOK_SCRIPT,
    async: true,
    timeoutSec: 5
  }]));
  // PreToolUse is a SYNCHRONOUS hook: agent-world blocks the Claude
  // CLI on this script's output so the user can Allow / Deny from
  // the browser. Timeout matches the server's permissionStore default
  // — the script respects AGENT_WORLD_PERMISSION_TIMEOUT_SEC too.
  return JSON.stringify({
    name: 'agent-world',
    description: 'Agent World visualizer hooks — status breadcrumbs + browser-driven permission approval.',
    version: '0.2.0',
    hooks: {
      ...statusHooks,
      PreToolUse: {
        command: PRE_TOOL_HOOK_SCRIPT,
        async: false,
        timeoutSec: 95
      }
    }
  }, null, 2);
}

function hookScriptContent() {
  // Bash script. Claude passes the hook event as a JSON object on stdin
  // (schema: https://code.claude.com/docs/en/hooks). We slurp stdin, add
  // ts + event name, and append one line to events/<pid>.jsonl.
  return `#!/usr/bin/env bash
# Auto-generated by agent-world/server/hookPluginInstaller.js
# Appends one JSON record per hook invocation to events/<pid>.jsonl.
set -euo pipefail
events_dir="${EVENTS_DIR}"
mkdir -p "$events_dir"
pid=\${CLAUDE_PID:-$$}
event="\${CLAUDE_HOOK_EVENT:-\${1:-Unknown}}"
ts=$(date +%s)
stdin_payload=""
if [ ! -t 0 ]; then
  stdin_payload=$(cat)
fi
record=$(printf '{"event":%s,"ts":%s,"pid":%s,"payload":%s}\\n' \\
  "$(printf '%s' "$event" | jq -Rs .)" \\
  "$ts" \\
  "$pid" \\
  "\${stdin_payload:-null}")
printf '%s\\n' "$record" >> "$events_dir/$pid.jsonl"
exit 0
`;
}

// PreToolUse hook — interactive permission prompt. Posts to the local
// agent-world server, waits for the browser (or timeout → `ask`), then
// writes the Claude Code hook-specific output JSON to stdout.
//
// Port is templated at install time. If the server isn't reachable,
// the script exits silently so Claude's default CLI prompt still runs.
function preToolHookScriptContent({ port = Number(process.env.PORT) || 3102 } = {}) {
  return `#!/usr/bin/env bash
# Auto-generated by agent-world/server/hookPluginInstaller.js
# Synchronous PreToolUse hook: routes permission requests to the
# agent-world browser UI. If the server is down or the user doesn't
# respond, we exit silently and Claude's normal CLI prompt fires.
set -uo pipefail

port="\${AGENT_WORLD_PORT:-${port}}"
timeout="\${AGENT_WORLD_PERMISSION_TIMEOUT_SEC:-92}"

# Slurp the stdin payload Claude passes us.
payload=""
if [ ! -t 0 ]; then
  payload=$(cat)
fi
if [ -z "$payload" ]; then
  exit 0
fi

# Extract fields with jq. If jq is missing, bail out quietly.
if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi
session_id=$(printf '%s' "$payload" | jq -r '.session_id // ""')
tool=$(printf '%s' "$payload" | jq -r '.tool_name // ""')
tool_input=$(printf '%s' "$payload" | jq -c '.tool_input // null')
cwd=$(printf '%s' "$payload" | jq -r '.cwd // ""')

body=$(jq -nc \\
  --arg sid "$session_id" \\
  --arg tool "$tool" \\
  --argjson toolInput "$tool_input" \\
  --arg cwd "$cwd" \\
  '{sessionId:$sid, tool:$tool, toolInput:$toolInput, cwd:$cwd}')

# POST and wait. -sS for silent-but-not-on-error, --max-time aligns
# with the server's 90 s deadline plus a small cushion.
response=$(curl -sS --max-time "$timeout" \\
  -H 'content-type: application/json' \\
  -X POST "http://127.0.0.1:$port/api/hooks/permission-request" \\
  --data "$body" 2>/dev/null)

if [ -z "$response" ]; then
  exit 0
fi

decision=$(printf '%s' "$response" | jq -r '.decision // "ask"')
reason=$(printf '%s' "$response" | jq -r '.reason // ""')

case "$decision" in
  allow|deny|ask) ;;
  *) decision=ask ;;
esac

# Emit the hook-specific output Claude Code expects. "ask" means:
# don't override — let the CLI prompt happen (exit with no output).
if [ "$decision" = "ask" ]; then
  exit 0
fi

jq -nc \\
  --arg decision "$decision" \\
  --arg reason "$reason" \\
  '{continue:true, hookSpecificOutput:{hookEventName:"PreToolUse", permissionDecision:$decision, permissionDecisionReason:$reason}}'

exit 0
`;
}

function buildInstall() {
  return {
    plan: [
      { op: 'mkdir', target: PLUGIN_DIR },
      { op: 'mkdir', target: HOOKS_DIR },
      { op: 'mkdir', target: EVENTS_DIR },
      { op: 'write', target: PLUGIN_JSON, content: pluginJsonContent() },
      { op: 'write', target: HOOK_SCRIPT, content: hookScriptContent(), mode: 0o755 },
      { op: 'write', target: PRE_TOOL_HOOK_SCRIPT, content: preToolHookScriptContent(), mode: 0o755 }
    ]
  };
}

function install({ dryRun = true } = {}) {
  const { plan } = buildInstall();
  const results = [];
  for (const step of plan) {
    if (step.op === 'mkdir') {
      const existed = fs.existsSync(step.target);
      if (!dryRun && !existed) fs.mkdirSync(step.target, { recursive: true });
      results.push({ ...step, existed, applied: !dryRun && !existed });
    } else if (step.op === 'write') {
      let unchanged = false;
      if (fs.existsSync(step.target)) {
        try {
          unchanged = fs.readFileSync(step.target, 'utf8') === step.content;
        } catch { /* ignore */ }
      }
      if (!dryRun && !unchanged) {
        fs.writeFileSync(step.target, step.content, 'utf8');
        if (step.mode) fs.chmodSync(step.target, step.mode);
      }
      results.push({ ...step, unchanged, applied: !dryRun && !unchanged });
    }
  }
  return { dryRun, results, pluginDir: PLUGIN_DIR };
}

function uninstall({ dryRun = true } = {}) {
  if (!fs.existsSync(PLUGIN_DIR)) {
    return { dryRun, removed: false, pluginDir: PLUGIN_DIR };
  }
  if (!dryRun) fs.rmSync(PLUGIN_DIR, { recursive: true, force: true });
  return { dryRun, removed: !dryRun, pluginDir: PLUGIN_DIR };
}

function status() {
  return {
    pluginDir: PLUGIN_DIR,
    installed: fs.existsSync(PLUGIN_JSON) && fs.existsSync(HOOK_SCRIPT),
    hookScriptExecutable: (() => {
      try {
        const st = fs.statSync(HOOK_SCRIPT);
        return Boolean(st.mode & 0o111);
      } catch { return false; }
    })(),
    eventsDir: EVENTS_DIR
  };
}

module.exports = {
  PLUGIN_DIR,
  HOOKS_DIR,
  EVENTS_DIR,
  PLUGIN_JSON,
  HOOK_SCRIPT,
  PRE_TOOL_HOOK_SCRIPT,
  HOOK_EVENTS,
  pluginJsonContent,
  hookScriptContent,
  preToolHookScriptContent,
  buildInstall,
  install,
  uninstall,
  status
};
