// Optional hook plugin installer. Writes to
// ~/.claude/plugins/agent-world/{plugin.json, hooks/status-hook.sh}
// and NEVER edits ~/.claude/settings.json.
//
// The hook script appends one JSON line per event into
// ~/.claude/plugins/agent-world/events/<pid>.jsonl, which the snapshotter
// consumes alongside (or instead of) claude-control's events dir.

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const PLUGIN_DIR = path.join(os.homedir(), '.claude', 'plugins', 'agent-world');
const HOOKS_DIR = path.join(PLUGIN_DIR, 'hooks');
const EVENTS_DIR = path.join(PLUGIN_DIR, 'events');
const PLUGIN_JSON = path.join(PLUGIN_DIR, 'plugin.json');
const HOOK_SCRIPT = path.join(HOOKS_DIR, 'status-hook.sh');

const HOOK_EVENTS = [
  'SessionStart', 'SessionEnd', 'Stop', 'UserPromptSubmit',
  'PermissionRequest', 'SubagentStart', 'SubagentStop',
  'PostToolUseFailure', 'CwdChanged'
];

function pluginJsonContent() {
  return JSON.stringify({
    name: 'agent-world',
    description: 'Append hook events to ~/.claude/plugins/agent-world/events/ for the Agent World visualizer.',
    version: '0.1.0',
    hooks: Object.fromEntries(HOOK_EVENTS.map(ev => [ev, {
      command: HOOK_SCRIPT,
      async: true,
      timeoutSec: 5
    }]))
  }, null, 2);
}

function hookScriptContent() {
  // Bash script. Claude passes the hook event as a JSON object on stdin
  // (schema: https://code.claude.com/docs/en/hooks). We slurp stdin, add
  // ts + event name, and append one line to events/<pid>.jsonl.
  return `#!/usr/bin/env bash
# Auto-generated by agent-world/server/hookPluginInstaller.js
# Appends one JSON record per hook invocation to events/<pid>.jsonl.
set -euo pipefail
events_dir="${EVENTS_DIR}"
mkdir -p "$events_dir"
pid=\${CLAUDE_PID:-$$}
event="\${CLAUDE_HOOK_EVENT:-\${1:-Unknown}}"
ts=$(date +%s)
stdin_payload=""
if [ ! -t 0 ]; then
  stdin_payload=$(cat)
fi
record=$(printf '{"event":%s,"ts":%s,"pid":%s,"payload":%s}\\n' \\
  "$(printf '%s' "$event" | jq -Rs .)" \\
  "$ts" \\
  "$pid" \\
  "\${stdin_payload:-null}")
printf '%s\\n' "$record" >> "$events_dir/$pid.jsonl"
exit 0
`;
}

function buildInstall() {
  return {
    plan: [
      { op: 'mkdir', target: PLUGIN_DIR },
      { op: 'mkdir', target: HOOKS_DIR },
      { op: 'mkdir', target: EVENTS_DIR },
      { op: 'write', target: PLUGIN_JSON, content: pluginJsonContent() },
      { op: 'write', target: HOOK_SCRIPT, content: hookScriptContent(), mode: 0o755 }
    ]
  };
}

function install({ dryRun = true } = {}) {
  const { plan } = buildInstall();
  const results = [];
  for (const step of plan) {
    if (step.op === 'mkdir') {
      const existed = fs.existsSync(step.target);
      if (!dryRun && !existed) fs.mkdirSync(step.target, { recursive: true });
      results.push({ ...step, existed, applied: !dryRun && !existed });
    } else if (step.op === 'write') {
      let unchanged = false;
      if (fs.existsSync(step.target)) {
        try {
          unchanged = fs.readFileSync(step.target, 'utf8') === step.content;
        } catch { /* ignore */ }
      }
      if (!dryRun && !unchanged) {
        fs.writeFileSync(step.target, step.content, 'utf8');
        if (step.mode) fs.chmodSync(step.target, step.mode);
      }
      results.push({ ...step, unchanged, applied: !dryRun && !unchanged });
    }
  }
  return { dryRun, results, pluginDir: PLUGIN_DIR };
}

function uninstall({ dryRun = true } = {}) {
  if (!fs.existsSync(PLUGIN_DIR)) {
    return { dryRun, removed: false, pluginDir: PLUGIN_DIR };
  }
  if (!dryRun) fs.rmSync(PLUGIN_DIR, { recursive: true, force: true });
  return { dryRun, removed: !dryRun, pluginDir: PLUGIN_DIR };
}

function status() {
  return {
    pluginDir: PLUGIN_DIR,
    installed: fs.existsSync(PLUGIN_JSON) && fs.existsSync(HOOK_SCRIPT),
    hookScriptExecutable: (() => {
      try {
        const st = fs.statSync(HOOK_SCRIPT);
        return Boolean(st.mode & 0o111);
      } catch { return false; }
    })(),
    eventsDir: EVENTS_DIR
  };
}

module.exports = {
  PLUGIN_DIR,
  HOOKS_DIR,
  EVENTS_DIR,
  PLUGIN_JSON,
  HOOK_SCRIPT,
  HOOK_EVENTS,
  pluginJsonContent,
  hookScriptContent,
  buildInstall,
  install,
  uninstall,
  status
};
